server:
  port: 9090

spring:
  profiles: test
  mvc:
    view:
      prefix: /WEB-INF/layout/
      suffix: .jsp
notification:
  run: Run Test!!

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

elasticsearch:
  index: tis
  remote:
    cluster:
      name: drms
    server: 10.10.0.242
    port: 19300


logging:
  level:
    root: warn
    com:
      simple:
        juni:
          core:
            config: info
          elasticsearch: info
